// Generated by delombok at Mon Apr 28 17:11:00 EEST 2014

import org.consulo.lombok.annotations.LazyInstance;

public class LazyInstanceMethod {
	@org.jetbrains.annotations.NotNull
	private static final com.intellij.openapi.util.NullableLazyValue<String> $getNullableStaticInstance$lazyValue = new com.intellij.openapi.util.NullableLazyValue<String>(){

		public String compute() {
			return com.intellij.openapi.components.ServiceManager.getService(String.class);
		}
	};
	@org.jetbrains.annotations.NotNull
	private final com.intellij.openapi.util.NullableLazyValue<String> $getNullableInstance$lazyValue = new com.intellij.openapi.util.NullableLazyValue<String>(){

		public String compute() {
			return com.intellij.openapi.components.ServiceManager.getService(String.class);
		}
	};
	@org.jetbrains.annotations.NotNull
	private static final com.intellij.openapi.util.NotNullLazyValue<String> $getStaticInstance$lazyValue = new com.intellij.openapi.util.NotNullLazyValue<String>(){

		public String compute() {
			return com.intellij.openapi.components.ServiceManager.getService(String.class);
		}
	};
	@org.jetbrains.annotations.NotNull
	private final com.intellij.openapi.util.NotNullLazyValue<String> $getInstance$lazyValue = new com.intellij.openapi.util.NotNullLazyValue<String>(){

		public String compute() {
			return com.intellij.openapi.components.ServiceManager.getService(String.class);
		}
	};


	@LazyInstance
	public String getInstance() {
		return $getInstance$lazyValue.getValue();
	}

	@LazyInstance
	public static String getStaticInstance() {
		return $getStaticInstance$lazyValue.getValue();
	}

	@LazyInstance(notNull = false)
	public String getNullableInstance() {
		return $getNullableInstance$lazyValue.getValue();
	}

	@LazyInstance(notNull = false)
	public static String getNullableStaticInstance() {
		return $getNullableStaticInstance$lazyValue.getValue();
	}
}