// Generated by delombok at Mon Apr 28 17:17:54 EEST 2014

import org.consulo.lombok.annotations.ApplicationService;

@ApplicationService(lazy = true)
public class OurLazyAppicationService {
	@org.jetbrains.annotations.NotNull
	private static final com.intellij.openapi.util.NotNullLazyValue<OurLazyAppicationService> $getInstance$lazyValue = new com.intellij.openapi.util.NotNullLazyValue<OurLazyAppicationService>(){

		public OurLazyAppicationService compute() {
			return com.intellij.openapi.components.ServiceManager.getService(OurLazyAppicationService.class);
		}
	};


	@org.jetbrains.annotations.NotNull
	@org.consulo.lombok.annotations.LazyInstance
	@java.lang.SuppressWarnings("all")
	public static OurLazyAppicationService getInstance() {
		return $getInstance$lazyValue.getValue();
	}
}