// Generated by delombok at Mon Oct 21 15:42:46 EEST 2013

import org.consulo.lombok.annotations.ApplicationService;

@ApplicationService
public class OutApplicationService {


	@org.jetbrains.annotations.NotNull
	@java.lang.SuppressWarnings("all")
	public static OutApplicationService getInstance() {
		return com.intellij.openapi.components.ServiceManager.getService(OutApplicationService.class);
	}
}