// Generated by delombok at Mon Oct 21 23:49:07 EEST 2013

import org.consulo.lombok.annotations.ArrayFactoryFields;

@ArrayFactoryFields
public class OutArrayFactoryFields {
	@org.jetbrains.annotations.NotNull
	public static final com.intellij.util.ArrayFactory<OutArrayFactoryFields> ARRAY_FACTORY = new com.intellij.util.ArrayFactory<OutArrayFactoryFields>(){

		public OutArrayFactoryFields[] create(int count) {
			return count == 0 ? EMPTY_ARRAY : new OutArrayFactoryFields[count];
		}
	};
	@org.jetbrains.annotations.NotNull
	public static final OutArrayFactoryFields[] EMPTY_ARRAY = new OutArrayFactoryFields[0];

}