// Generated by delombok at Mon Oct 21 18:20:20 EEST 2013

import org.consulo.lombok.annotations.Bundle;

@Bundle("messages.ErrorBundle")
public class OutBundleManager extends com.intellij.AbstractBundle {
	private static final OutBundleManager ourInstance = new OutBundleManager();

	@java.lang.SuppressWarnings("all")
	private OutBundleManager() {
		super("messages.ErrorBundle");
	}

	@org.jetbrains.annotations.NotNull
	@java.lang.SuppressWarnings("all")
	public static java.lang.String message(@org.jetbrains.annotations.PropertyKey(resourceBundle = "messages.ErrorBundle") java.lang.String key) {
		return ourInstance.getMessage(key);
	}

	@org.jetbrains.annotations.NotNull
	@java.lang.SuppressWarnings("all")
	public static java.lang.String message(@org.jetbrains.annotations.PropertyKey(resourceBundle = "messages.ErrorBundle") java.lang.String key, java.lang.Object... args) {
		return ourInstance.getMessage(key, args);
	}
}