// Generated by delombok at Tue Oct 22 00:16:37 EEST 2013

import org.consulo.lombok.annotations.Bundle;

@Bundle
public class OutBundle2 extends com.intellij.AbstractBundle {
	private static final OutBundle2 ourInstance = new OutBundle2();

	@java.lang.SuppressWarnings("all")
	private OutBundle2() {
		super("messages.OutBundle2");
		return;
	}

	@org.jetbrains.annotations.NotNull
	@java.lang.SuppressWarnings("all")
	public static java.lang.String message(@org.jetbrains.annotations.PropertyKey(resourceBundle = "messages.OutBundle2") java.lang.String key) {
		return ourInstance.getMessage(key);
	}

	@org.jetbrains.annotations.NotNull
	@java.lang.SuppressWarnings("all")
	public static java.lang.String message(@org.jetbrains.annotations.PropertyKey(resourceBundle = "messages.OutBundle2") java.lang.String key, java.lang.Object... args) {
		return ourInstance.getMessage(key, args);
	}
}