// Generated by delombok at Tue Oct 22 00:16:37 EEST 2013

import org.consulo.lombok.annotations.Bundle;

@Bundle("messages.ErrorBundle")
public class OutBundle extends com.intellij.AbstractBundle {
	private static final OutBundle ourInstance = new OutBundle();

	@java.lang.SuppressWarnings("all")
	private OutBundle() {
		super("messages.ErrorBundle");
		return;
	}

	@org.jetbrains.annotations.NotNull
	@java.lang.SuppressWarnings("all")
	public static java.lang.String message(@org.jetbrains.annotations.PropertyKey(resourceBundle = "messages.ErrorBundle") java.lang.String key) {
		return ourInstance.getMessage(key);
	}

	@org.jetbrains.annotations.NotNull
	@java.lang.SuppressWarnings("all")
	public static java.lang.String message(@org.jetbrains.annotations.PropertyKey(resourceBundle = "messages.ErrorBundle") java.lang.String key, java.lang.Object... args) {
		return ourInstance.getMessage(key, args);
	}
}