// Generated by delombok at Mon Oct 21 15:51:29 EEST 2013

public class OutLogger {
	private static final com.intellij.openapi.diagnostic.Logger LOGGER = com.intellij.openapi.diagnostic.Logger.getInstance(OutLogger.class);

}
