// Generated by delombok at Mon Oct 21 16:09:41 EEST 2013

import org.consulo.lombok.annotations.ModuleService;

@ModuleService
public class OutModuleService {


	@org.jetbrains.annotations.NotNull
	@java.lang.SuppressWarnings("all")
	public static OutModuleService getInstance(@org.jetbrains.annotations.NotNull com.intellij.openapi.module.Module module) {
		return com.intellij.openapi.module.ModuleServiceManager.getService(module, OutModuleService.class);
	}
}