// Generated by delombok at Mon Oct 21 16:10:01 EEST 2013

import org.consulo.lombok.annotations.ProjectService;

@ProjectService
public class OutProjectService {


	@org.jetbrains.annotations.NotNull
	@java.lang.SuppressWarnings("all")
	public static OutProjectService getInstance(@org.jetbrains.annotations.NotNull com.intellij.openapi.project.Project project) {
		return com.intellij.openapi.components.ServiceManager.getService(project, OutProjectService.class);
	}
}